jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up kubectl
        uses: actions/setup-kubectl@v2
        with:
          version: 'v1.21.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f nginx-deployment.yaml
