name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        echo "${{ secrets.CLIENT_CERT }}" > $HOME/.kube/client.crt
        echo "${{ secrets.CLIENT_KEY }}" > $HOME/.kube/client.key
        echo "${{ secrets.CA_CRT }}" > $HOME/.kube/ca.crt

    - name: Deploy to Kubernetes
      run: kubectl apply -f nginx-deployment.yaml --kubeconfig=$HOME/.kube/config
