name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          mkdir -p /tmp/.kube
          echo "${{ secrets.KUBECONFIG }}" > /tmp/.kube/config

      - name: Check kubeconfig content
        run: cat /tmp/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1  # Используем актуальный action от Azure

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=/tmp/.kube/config apply -f nginx-deployment.yaml
