name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          echo "${{ secrets.KUBE_CA_CERT }}" > $HOME/.kube/ca.crt
          echo "${{ secrets.KUBE_CLIENT_CERT }}" > $HOME/.kube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" > $HOME/.kube/client.key

      - name: Check kubeconfig content
        run: cat $HOME/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=$HOME/.kube/config apply -f nginx-deployment.yaml
