name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          echo "${{ secrets.CLIENT_CERT }}" > /tmp/client.crt
          echo "${{ secrets.CLIENT_KEY }}" > /tmp/client.key
          echo "${{ secrets.CA_CERT }}" > /tmp/ca.crt

      - name: Configure kubectl
        run: |
          kubectl config set-credentials minikube \
            --client-certificate=/tmp/client.crt \
            --client-key=/tmp/client.key
          kubectl config set-cluster minikube \
            --certificate-authority=/tmp/ca.crt \
            --server=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
          kubectl config set-context minikube --cluster=minikube --user=minikube
          kubectl config use-context minikube

      - name: Deploy to Kubernetes
        run: kubectl apply -f nginx-deployment.yaml
